# Generated by Django 5.0.7 on 2024-09-26 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_studentlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlist',
            name='user',
        ),
    ]
